export const STORE_LIST = 'STORE_LIST';
export const STORE_LIST_SUCCESS = 'STORE_LIST_SUCCESS';
export const STORE_LIST_FAIL = 'STORE_LIST_FAIL';
export const STORE_LIST_CLEAR = 'STORE_LIST_CLEAR';

export const STORE_LIST_ALL = 'STORE_LIST_ALL';
export const STORE_LIST_ALL_SUCCESS = 'STORE_LIST_ALL_SUCCESS';
export const STORE_LIST_ALL_FAIL = 'STORE_LIST_ALL_FAIL';
export const STORE_LIST_ALL_CLEAR = 'STORE_LIST_ALL_CLEAR';

export const STORE_LIST_UPDATE = 'STORE_LIST_ALL';
export const STORE_LIST_UPDATE_SUCCESS = 'STORE_LIST_ALL_SUCCESS';
export const STORE_LIST_UPDATE_FAIL = 'STORE_LIST_ALL_FAIL';

export const STORE_ITEM_LOAD = 'STORE_ITEM_LOAD';
export const STORE_ITEM_LOAD_SUCCESS = 'STORE_ITEM_LOAD_SUCCESS';
export const STORE_ITEM_LOAD_FAIL = 'STORE_ITEM_LOAD_FAIL';
export const STORE_ITEM_CLEAR = 'STORE_ITEM_CLEAR';

export const STORE_SIMPLE_LOAD = 'STORE_SIMPLE_LOAD';
export const STORE_SIMPLE_LOAD_SUCCESS = 'STORE_LOAD_SIMPLE_SUCCESS';
export const STORE_SIMPLE_LOAD_FAIL = 'STORE_LOAD_SIMPLE_FAIL';
export const STORE_SIMPLE_CLEAR = 'STORE_SIMPLE_CLEAR';

export const STORE_ITEM_CREATE = 'STORE_ITEM_CREATE';
export const STORE_ITEM_CREATE_SUCCESS = 'STORE_ITEM_CREATE_SUCCESS';
export const STORE_ITEM_CREATE_FAIL = 'STORE_ITEM_CREATE_FAIL';

export const STORE_ITEM_EDIT = 'STORE_ITEM_EDIT';
export const STORE_ITEM_EDIT_SUCCESS = 'STORE_ITEM_EDIT_SUCCESS';
export const STORE_ITEM_EDIT_FAIL = 'STORE_ITEM_EDIT_FAIL';

export const STORE_ITEM_UPDATE = 'STORE_ITEM_UPDATE';
export const STORE_ITEM_UPDATE_SUCCESS = 'STORE_ITEM_UPDATE_SUCCESS';
export const STORE_ITEM_UPDATE_FAIL = 'STORE_ITEM_UPDATE_FAIL';

export const STORE_ITEM_UPDATE_DEEP = 'STORE_ITEM_UPDATE_DEEP';
export const STORE_ITEM_UPDATE_DEEP_SUCCESS = 'STORE_ITEM_UPDATE_SUCCESS_DEEP';
export const STORE_ITEM_UPDATE_DEEP_FAIL = 'STORE_ITEM_UPDATE_FAIL_DEEP';

export const STORE_ITEM_CREATE_DEEP = 'STORE_ITEM_CREATE_DEEP';
export const STORE_ITEM_CREATE_DEEP_SUCCESS = 'STORE_ITEM_CREATE_DEEP_SUCCESS';
export const STORE_ITEM_CREATE_DEEP_FAIL = 'STORE_ITEM_CREATE_DEEP_FAIL';

export const STORE_ITEM_DELETE_DEEP = 'STORE_ITEM_DELETE_DEEP';
export const STORE_ITEM_DELETE_DEEP_SUCCESS = 'STORE_ITEM_DELETE_DEEP_SUCCESS';
export const STORE_ITEM_DELETE_DEEP_FAIL = 'STORE_ITEM_DELETE_DEEP_FAIL';

export const STORE_ITEM_LOCAL_UPDATE = 'STORE_ITEM_LOCAL_UPDATE';
export const STORE_ITEM_LOCAL_UPDATE_SUCCESS = 'STORE_ITEM_LOCAL_UPDATE_SUCCESS';
export const STORE_ITEM_LOCAL_UPDATE_FAIL = 'STORE_ITEM_LOCAL_UPDATE_FAIL';

export const STORE_ITEM_LOCAL_DEEP_DELETE = 'STORE_ITEM_LOCAL_DEEP_DELETE';

export const STORE_ITEM_DELETE = 'STORE_ITEM_DELETE';
export const STORE_ITEM_DELETE_SUCCESS = 'STORE_ITEM_DELETE_SUCCESS';
export const STORE_ITEM_DELETE_FAIL = 'STORE_ITEM_DELETE_FAIL';

export const STORE_ITEM_PROPERTY = 'STORE_ITEM_PROPERTY';
export const STORE_ITEM_PROPERTY_SUCCESS = 'STORE_ITEM_PROPERTY_SUCCESS';
export const STORE_ITEM_PROPERTY_FAIL = 'STORE_ITEM_PROPERTY_FAIL';

export const STORE_ITEM_CLEAR_NETWORK_STATE = 'STORE_ITEM_CLEAR_NETWORK_STATE';

export const STORE_STACK_ITEM_LOAD = 'STORE_STACK_ITEM_LOAD';
export const STORE_STACK_ITEM_LOAD_SUCCESS = 'STORE_STACK_ITEM_LOAD_SUCCESS';
export const STORE_STACK_ITEM_LOAD_FAILED = 'STORE_STACK_ITEM_LOAD_FAILED';
export const STORE_STACK_ITEM_CLEAR = 'STORE_STACK_ITEM_CLEAR';

export const reducerIndex = 'store';
export const reducerItem = 'item';
