'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var STORE_LIST = exports.STORE_LIST = 'STORE_LIST';
var STORE_LIST_SUCCESS = exports.STORE_LIST_SUCCESS = 'STORE_LIST_SUCCESS';
var STORE_LIST_FAIL = exports.STORE_LIST_FAIL = 'STORE_LIST_FAIL';
var STORE_LIST_CLEAR = exports.STORE_LIST_CLEAR = 'STORE_LIST_CLEAR';

var STORE_LIST_ALL = exports.STORE_LIST_ALL = 'STORE_LIST_ALL';
var STORE_LIST_ALL_SUCCESS = exports.STORE_LIST_ALL_SUCCESS = 'STORE_LIST_ALL_SUCCESS';
var STORE_LIST_ALL_FAIL = exports.STORE_LIST_ALL_FAIL = 'STORE_LIST_ALL_FAIL';
var STORE_LIST_ALL_CLEAR = exports.STORE_LIST_ALL_CLEAR = 'STORE_LIST_ALL_CLEAR';

var STORE_ITEM_LOAD = exports.STORE_ITEM_LOAD = 'STORE_ITEM_LOAD';
var STORE_ITEM_LOAD_SUCCESS = exports.STORE_ITEM_LOAD_SUCCESS = 'STORE_ITEM_LOAD_SUCCESS';
var STORE_ITEM_LOAD_FAIL = exports.STORE_ITEM_LOAD_FAIL = 'STORE_ITEM_LOAD_FAIL';
var STORE_ITEM_CLEAR = exports.STORE_ITEM_CLEAR = 'STORE_ITEM_CLEAR';

var STORE_SIMPLE_LOAD = exports.STORE_SIMPLE_LOAD = 'STORE_SIMPLE_LOAD';
var STORE_SIMPLE_LOAD_SUCCESS = exports.STORE_SIMPLE_LOAD_SUCCESS = 'STORE_LOAD_SIMPLE_SUCCESS';
var STORE_SIMPLE_LOAD_FAIL = exports.STORE_SIMPLE_LOAD_FAIL = 'STORE_LOAD_SIMPLE_FAIL';
var STORE_SIMPLE_CLEAR = exports.STORE_SIMPLE_CLEAR = 'STORE_SIMPLE_CLEAR';

var STORE_ITEM_CREATE = exports.STORE_ITEM_CREATE = 'STORE_ITEM_CREATE';
var STORE_ITEM_CREATE_SUCCESS = exports.STORE_ITEM_CREATE_SUCCESS = 'STORE_ITEM_CREATE_SUCCESS';
var STORE_ITEM_CREATE_FAIL = exports.STORE_ITEM_CREATE_FAIL = 'STORE_ITEM_CREATE_FAIL';

var STORE_ITEM_EDIT = exports.STORE_ITEM_EDIT = 'STORE_ITEM_EDIT';
var STORE_ITEM_EDIT_SUCCESS = exports.STORE_ITEM_EDIT_SUCCESS = 'STORE_ITEM_EDIT_SUCCESS';
var STORE_ITEM_EDIT_FAIL = exports.STORE_ITEM_EDIT_FAIL = 'STORE_ITEM_EDIT_FAIL';

var STORE_ITEM_UPDATE = exports.STORE_ITEM_UPDATE = 'STORE_ITEM_UPDATE';
var STORE_ITEM_UPDATE_SUCCESS = exports.STORE_ITEM_UPDATE_SUCCESS = 'STORE_ITEM_UPDATE_SUCCESS';
var STORE_ITEM_UPDATE_FAIL = exports.STORE_ITEM_UPDATE_FAIL = 'STORE_ITEM_UPDATE_FAIL';

var STORE_ITEM_UPDATE_DEEP = exports.STORE_ITEM_UPDATE_DEEP = 'STORE_ITEM_UPDATE_DEEP';
var STORE_ITEM_UPDATE_DEEP_SUCCESS = exports.STORE_ITEM_UPDATE_DEEP_SUCCESS = 'STORE_ITEM_UPDATE_SUCCESS_DEEP';
var STORE_ITEM_UPDATE_DEEP_FAIL = exports.STORE_ITEM_UPDATE_DEEP_FAIL = 'STORE_ITEM_UPDATE_FAIL_DEEP';

var STORE_ITEM_CREATE_DEEP = exports.STORE_ITEM_CREATE_DEEP = 'STORE_ITEM_CREATE_DEEP';
var STORE_ITEM_CREATE_DEEP_SUCCESS = exports.STORE_ITEM_CREATE_DEEP_SUCCESS = 'STORE_ITEM_CREATE_DEEP_SUCCESS';
var STORE_ITEM_CREATE_DEEP_FAIL = exports.STORE_ITEM_CREATE_DEEP_FAIL = 'STORE_ITEM_CREATE_DEEP_FAIL';

var STORE_ITEM_DELETE_DEEP = exports.STORE_ITEM_DELETE_DEEP = 'STORE_ITEM_DELETE_DEEP';
var STORE_ITEM_DELETE_DEEP_SUCCESS = exports.STORE_ITEM_DELETE_DEEP_SUCCESS = 'STORE_ITEM_DELETE_DEEP_SUCCESS';
var STORE_ITEM_DELETE_DEEP_FAIL = exports.STORE_ITEM_DELETE_DEEP_FAIL = 'STORE_ITEM_DELETE_DEEP_FAIL';

var STORE_ITEM_LOCAL_UPDATE = exports.STORE_ITEM_LOCAL_UPDATE = 'STORE_ITEM_LOCAL_UPDATE';
var STORE_ITEM_LOCAL_UPDATE_SUCCESS = exports.STORE_ITEM_LOCAL_UPDATE_SUCCESS = 'STORE_ITEM_LOCAL_UPDATE_SUCCESS';
var STORE_ITEM_LOCAL_UPDATE_FAIL = exports.STORE_ITEM_LOCAL_UPDATE_FAIL = 'STORE_ITEM_LOCAL_UPDATE_FAIL';

var STORE_ITEM_LOCAL_DEEP_DELETE = exports.STORE_ITEM_LOCAL_DEEP_DELETE = 'STORE_ITEM_LOCAL_DEEP_DELETE';

var STORE_ITEM_DELETE = exports.STORE_ITEM_DELETE = 'STORE_ITEM_DELETE';
var STORE_ITEM_DELETE_SUCCESS = exports.STORE_ITEM_DELETE_SUCCESS = 'STORE_ITEM_DELETE_SUCCESS';
var STORE_ITEM_DELETE_FAIL = exports.STORE_ITEM_DELETE_FAIL = 'STORE_ITEM_DELETE_FAIL';

var STORE_ITEM_PROPERTY = exports.STORE_ITEM_PROPERTY = 'STORE_ITEM_PROPERTY';
var STORE_ITEM_PROPERTY_SUCCESS = exports.STORE_ITEM_PROPERTY_SUCCESS = 'STORE_ITEM_PROPERTY_SUCCESS';
var STORE_ITEM_PROPERTY_FAIL = exports.STORE_ITEM_PROPERTY_FAIL = 'STORE_ITEM_PROPERTY_FAIL';

var STORE_ITEM_CLEAR_NETWORK_STATE = exports.STORE_ITEM_CLEAR_NETWORK_STATE = 'STORE_ITEM_CLEAR_NETWORK_STATE';

var STORE_STACK_ITEM_LOAD = exports.STORE_STACK_ITEM_LOAD = 'STORE_STACK_ITEM_LOAD';
var STORE_STACK_ITEM_LOAD_SUCCESS = exports.STORE_STACK_ITEM_LOAD_SUCCESS = 'STORE_STACK_ITEM_LOAD_SUCCESS';
var STORE_STACK_ITEM_LOAD_FAILED = exports.STORE_STACK_ITEM_LOAD_FAILED = 'STORE_STACK_ITEM_LOAD_FAILED';
var STORE_STACK_ITEM_CLEAR = exports.STORE_STACK_ITEM_CLEAR = 'STORE_STACK_ITEM_CLEAR';

var reducerIndex = exports.reducerIndex = 'store';
var reducerItem = exports.reducerItem = 'item';